spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.17.130:3306/bargain
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  redis:
    database: 0
    host: 192.168.17.130
    port: 6379
    password: 123456   # 密码（默认为空）
    timeout: 10000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 100  # 连接池最大连接数（使用负值表示没有限制）      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
        max-wait: 100ms
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  rabbitmq:
    host: 192.168.17.130
    port: 5672
    username: admin
    password: admin